<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(htmlclass, , no-js, , body1if_2026c3</name>
   <tag></tag>
   <elementGuidId>a7585993-5cc7-4e90-965f-c07a3a472b48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='checkout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;checkout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ravemodal-dev.herokuapp.com/?PBFPubKey=FLWPUBK_TEST-b393100d50d8109d953760d5093e5d2e-X&amp;txref=VMOZG558LI&amp;amount=2000&amp;currency=NGN&amp;country=NG&amp;payment_options=card%2Cussd%2Caccount%2Cbanktransfer%2Cqr%2Cbarter%2Cpayattitude%2Cmobilemoneyghana&amp;redirect_url=https%3A%2F%2Fapi.staging.myautochek.com%2Fpayments&amp;customer_firstname=fabian&amp;customer_lastname=amicki&amp;customer_email=ojbauer24%40gmail.com&amp;init_url=https%253A%252F%252Fravemodal-dev.herokuapp.com%252Fv3%252Fhosted%252Fpay%252F70bbce9d4d1f99a8f812</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='checkout']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
